### ISSUE TITLE
Crashes with App update 1.0.0

### ISSUE THREAD

**Issue by Jpersh27** [CookieJarApps/VideoDL#10]
@CookieJarApps Hello 

• With the release of today's update the app crashes constantly everytime you remove a file from the downloads list or from your device after you remove more than 2 files in a row. 

• I will attach Screenshots below indicating the crash.

• The Apk version I downloaded was: app-arm64-v8a-release.apk

• Android version- Android 10 Q.

• Device type- Nokia 5.3.

![IMG_20210517_011104.jpg](https://user-images.githubusercontent.com/77606699/118435970-edca7d00-b6ad-11eb-806a-6ef3c656a84f.jpg)

![IMG_20210517_011023.jpg](https://user-images.githubusercontent.com/77606699/118435982-f1f69a80-b6ad-11eb-8531-eb54c4480f96.jpg)

**Comment by CookieJarApps** [comment]
Thanks for letting me know - I'll work on a fix ASAP.

**Comment by Jpersh27** [comment]
@CookieJarApps Hello and thank you.

1.) When do you expect you'll be able to release a new update that will address these crashes?

**Comment by CookieJarApps** [comment]
> @CookieJarApps Hello and thank you.
> 
> 1.) When do you expect you'll be able to release a new update that will address these crashes? 

I'll make sure it's done by Friday evening at the latest, and then I'll follow it with a bigger update this weekend.
