### ISSUE TITLE
Improvements/Additions to help improve app usability-

### ISSUE THREAD

**Issue by Jpersh27** [CookieJarApps/VideoDL#11]
Hello @CookieJarApps I hope all is well with you. I have a few potential suggestions/additions that would help improve the usability of your Video DL application.

1.) Speed up the process of Obtaining the Video Urls in the application.

• When processing a Video URL that is copied and pasted in the apps search bar or by using the native share function within Android the app takes a long time to process requests and sometimes the app hangs and doesn't find the associated URL until you do it several times over or force close and Relaunch the application. 

2.) Further accelerate download speeds by using Multi threading. Starting with 16 as the default and allow users to further choose all the way up to 32 parts.  

3.) Create an empty file/pre allocate space when the file is cached/created to help accelerate downloading speeds.

4.) Show the estimated or actual file size for each video format that is fetched from the link you put in the Video URL box. 

• Sometimes the file size is not displayed and just says 0 B. I will attach a screenshot showing what I mean down below. ![IMG_20210721_210510.jpg](https://user-images.githubusercontent.com/77606699/126577828-3ee8be13-f5cb-47fe-8f54-9bcbf2d8ca1d.jpg)

Thank you and I hope that you consider these potential ideas as additions to your application.

**Comment by Jpersh27** [comment]
Hello @CookieJarApps I just wanted to see if you saw the separate email I sent to you about 3 weeks ago along with this open issue for the application.
I haven't heard anything back from you and I am just wondering if this project is abandoned? Or you just don't have anymore time to work on it and don't have any plans for future updates? 

Thank you and looking forward to your reply.

**Comment by CookieJarApps** [comment]
The project isn't abandoned - I've been away for a while but I'll update the app again soon.

The process of getting the video download URLs in the app is handled by youtube-dl, so there probably isn't anything I can do to speed it up, but the app shouldn't freeze or crash during the process. I'll look into that issue.

The way downloading currently works is that a blank file is created in the app's storage, the video is downloaded into that and then the file is moved into the download location. I'll carry on working on a rewrite of the download part of the app.

The file size is also fetched by youtube-dl, but it's odd it's returning 0B. I'll look into that too, and if I can't fix it, I'll make the app fallback to an estimated size calculated from resolution, filetype and length.

**Comment by Jpersh27** [comment]
Hello @CookieJarApps 

1.) I was wondering if you have any ETA on when you'll be releasing the next update to the application? 

2.) Lastly what new updates or fixes will be included in this new update to the application?

• As always thanks again and looking forward to your reply soon. Hope you have a nice rest of your week this week as well.

**Comment by Jpersh27** [comment]
@CookieJarApps It has been almost 3 months now since I have received a reply from you and I am just wondering if you have any intentions of returning to this project In the near future or ever?

• I'd hate to see this app go to waste and no longer receive further updates or improvements. 

• At this time it desperately needs some updates and additional features to better suite it for newer Android devices.

**Comment by CookieJarApps** [comment]
> @CookieJarApps It has been almost 3 months now since I have received a reply from you and I am just wondering if you have any intentions of returning to this project In the near future or ever?
> 
> • I'd hate to see this app go to waste and no longer receive further updates or improvements. 
> 
> • At this time it desperately needs some updates and additional features to better suite it for newer Android devices. 

Sorry! I haven't been very active for a while now, but I've got time to work on my apps again. I've just started working on a new update now.

**Comment by CookieJarApps** [comment]
The current plans for the new update are:

- New app design (done)
- youtube-dl replaced with yt-dlp (mostly done)
- Revamp of downloader, including splitting downloads into parts

**Comment by Jpersh27** [comment]
Hello @CookieJarApps Thank you for getting back to me and working on the app again. It sounds like a good plan so far to me and I'm looking forward to the next update.

1.) When do you expect you'll be able to release an update with those listed improvements? 

2.) Besides the ones listed, do you have any other ideas for the app that you would like to add after this update is released?

Thank you again!

**Comment by Jpersh27** [comment]
@CookieJarApps  Any new updates yet that you can provide regarding the next app update?

**Comment by CookieJarApps** [comment]
> @CookieJarApps  Any new updates yet that you can provide regarding the next app update? 

Sorry for the late reply! I'm aiming for a release this weekend or next week, and at the moment I don't have any other features planned, but I'm open for suggestions.

**Comment by Jpersh27** [comment]
@CookieJarApps Are you still planning on releasing the new update this weekend as planned? Or No?

**Comment by Jpersh27** [comment]
Hello @CookieJarApps, have you had the chance to see my last comment yet regarding the application release this weekend?? Or will you be pushing back the release again???

**Comment by CookieJarApps** [comment]
It's nearly done and should be released today.

**Comment by Jpersh27** [comment]
@CookieJarApps Thank you for the update. I will be looking forward to trying it out hopefully later today. 

1.) Are you still open to suggestions for new features??

• I do have a few more that I would like to see added but I want to test out the new build first before suggesting anything else.

**Comment by CookieJarApps** [comment]
v3.0 is available now. I'm open to suggestions for the next update though!

**Comment by Jpersh27** [comment]
@CookieJarApps Videos are broken and can't be played or recognized by media players after they are downloaded. I tried downloading in both 1920×1080p and 1280×720p. Anytime I try playing the videos on my phone with either VLC or MX player I am greeted with a video time of 00:00 and 00:00 and an error saying the video file can't be recognized. 

• Reverting back to youtube-dl instead of yt-dlp might help solve the current issues. In the previous version of the app 2.0 the downloaded video files were recognized and fine when being played on my devices. 

• I also tried using the console command and I get an error message and it is still showing up as youtube-dl instead of yt-dlp.

![Screenshot_20211101-045712.png](https://user-images.githubusercontent.com/77606699/139647297-676f6174-5880-4088-acce-2788f16002b6.png)

**Comment by CookieJarApps** [comment]
> @CookieJarApps Videos are broken and can't be played or recognized by media players after they are downloaded. I tried downloading in both 1920×1080p and 1280×720p. Anytime I try playing the videos on my phone with either VLC or MX player I am greeted with a video time of 00:00 and 00:00 and an error saying the video file can't be recognized. 
> 
> • Reverting back to youtube-dl instead of yt-dlp might help solve the current issues. In the previous version of the app 2.0 the downloaded video files were recognized and fine when being played on my devices. 
> 
> • I also tried using the console command and I get an error message and it is still showing up as youtube-dl instead of yt-dlp.
> 
> ![Screenshot_20211101-045712.png](https://user-images.githubusercontent.com/77606699/139647297-676f6174-5880-4088-acce-2788f16002b6.png)

I recommend you try uninstalling and reinstalling the app, then. The app may not be clearing the older version's files correctly. The console should still show "youtube-dl" as the command name is kept the same in yt-dlp, but should work as usual (for examples if you were to enter "--help").

**Comment by Jpersh27** [comment]
@CookieJarApps Already uninstalled the app twice and I also installed and tried using the app on 2 of my other devices and still encountered the same issues.

**Comment by CookieJarApps** [comment]
> @CookieJarApps Already uninstalled the app twice and I also installed and tried using the app on 2 of my other devices and still encountered the same issues. 

Could you try running "--help" in the command tab? Thanks.

**Comment by Jpersh27** [comment]
@CookieJarApps Now what??

**Comment by CookieJarApps** [comment]
> @CookieJarApps Now what?? 

Could you try downloading a YouTube video with the app to see if that functions correctly?

**Comment by Jpersh27** [comment]
@CookieJarApps YouTube works just fine for both Videos and Music files.

• However I am still having issues with video sizes and Video files not being recognized properly on the following 3 websites I have listed down below-

1.) Pornhub.com (NSFW Website)

2.) Xhamster.com (NSFW Website)

3.) Xvideos.com (NSFW Website)

![Screenshot_20211103-164210.png](https://user-images.githubusercontent.com/77606699/140191251-b66f58d4-0fe0-4fe7-9103-7e9f296d3051.png)

![Screenshot_20211103-164338.png](https://user-images.githubusercontent.com/77606699/140191264-986bdbb7-487a-40f8-89d9-e2fc691ec8fe.png)

![Screenshot_20211103-164519~2.png](https://user-images.githubusercontent.com/77606699/140191271-435fc4fc-c020-4988-b5de-afb916d39e3e.png)

![Screenshot_20211103-164658~2.png](https://user-images.githubusercontent.com/77606699/140191289-75a8c9ff-7400-44a2-ba91-0af123a7eff9.png)

![Screenshot_20211103-164615~2.png](https://user-images.githubusercontent.com/77606699/140191297-e3448179-510e-40ce-ac55-29324ab42d13.png)

• I have blurred out the screenshots of the video files and have blurred out the name of the video files. 

1.) Why does it have Video files listed with various different resolutions that are inaccurate and not in the correct format?

• For example such as: 0×1080, 0×720, 0×480, and 0×240. 

• In addition if you where to download one of those files with the incorrect resolution they willn't play correctly and will have the time displayed as 00:00 to 00:00 and you will be unable to chose which part of the video you would like to start at.

• I mainly use the application for other websites besides YouTube and rarely have problems with downloading any file from YouTube but would like to see the app be able to download video files from various different sources.

**Comment by Jpersh27** [comment]
@CookieJarApps I looked on the yt-dlp repository on found the supported website list and went through it and found that the 3 websites I am having trouble with are supported websites.

• https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md

![Screenshot_20211103-172841.png](https://user-images.githubusercontent.com/77606699/140195841-df4c6bf7-f990-4d0f-b743-9b607cc4fc98.png)

![Screenshot_20211103-172850.png](https://user-images.githubusercontent.com/77606699/140195853-83ced7f5-3828-44d4-a976-baf154006e21.png)

![Screenshot_20211103-172917.png](https://user-images.githubusercontent.com/77606699/140195864-a2f3813a-b461-4ffb-b386-c36053ada747.png)

1.) Is there any work around that you know of @CookieJarApps that I can use the console commands to help the application display the video file format and size correctly? Or is it a separate issue altogether?

**Comment by Jpersh27** [comment]
@CookieJarApps Have you had a chance to review my last two comments yet in reply to your question the other day?

**Comment by Jpersh27** [comment]
> @CookieJarApps Have you had a chance to review my last two comments yet in reply to your question the other day? 

1.) Is that a yes or No @CookieJarApps ???

**Comment by CookieJarApps** [comment]
Sorry for the late reply, I haven't had time to fully look into the issue yet until now - I think there might be some issues with the extractors in yt-dlp for these sites. I'll verify that it's a yt-dlp issue and then I'll have a look at the extractors and see if I can see what's causing the issues. Then I'll either open a pull request or issue for yt-dlp if I can find a specific issue.

**Comment by Jpersh27** [comment]
@CookieJarApps Thank you for getting back to me and for the explanation also. 

1.) Any timeframe for when you think you'll be able to get around to looking into the specific issues? 

2.) Anything I can do in the meantime to help or look into what's causing the issues? 

3.) Lastly is there any work around at this current time to the download issues with these specific websites? 

Thanks again! and I will be looking forward to hearing from you again soon @CookieJarApps

**Comment by Jpersh27** [comment]
Hello again @CookieJarApps 

1.) I wondering if you have had any opportunity to look into the issue yet regarding the 3 websites and the extractors in yt-dlp?

**Comment by CookieJarApps** [comment]
Could you try entering `-f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' URL_GOES_HERE` into the console tab with the video URL that isn't working in the app. Thanks!

**Comment by Jpersh27** [comment]
@CookieJarApps  I used a random URL for each one of the 3 websites I am having issues with and this is what was outputted in the console command.

![Screenshot_20211107-075121.png](https://user-images.githubusercontent.com/77606699/140645929-50c748e5-1192-4641-abd9-d3053d9dbabe.png)

![Screenshot_20211107-075412.png](https://user-images.githubusercontent.com/77606699/140645934-d22dcccc-b1a9-4bcd-a848-719fe803e7ba.png)

![Screenshot_20211107-075649.png](https://user-images.githubusercontent.com/77606699/140645936-f51c75a4-6d65-4f59-8cd9-e5b6aa2dbc49.png)

**Comment by Jpersh27** [comment]
@CookieJarApps Here is what comes up in the console command when I enter just the URLs by themselves. Each one of the three websites is showing a number of download fragments varying in number.

**Comment by CookieJarApps** [comment]
Could you try without the square brackets around the URL - just with the URL on its own? Thanks!

**Comment by Jpersh27** [comment]
@CookieJarApps With brackets-

![Screenshot_20211107-085552~2.png](https://user-images.githubusercontent.com/77606699/140648094-1c27595b-413c-4b96-a6f4-9759351d7e86.png)

![Screenshot_20211107-085454~2.png](https://user-images.githubusercontent.com/77606699/140648097-8cf54b91-9cd8-4ec6-b52f-52fcb41ff631.png)

![Screenshot_20211107-085419.png](https://user-images.githubusercontent.com/77606699/140648102-1d53b684-efa1-45e7-aed2-528b169e6e78.png)

**Comment by Jpersh27** [comment]
@CookieJarApps Without brackets-

![Screenshot_20211107-084431~3.png](https://user-images.githubusercontent.com/77606699/140648123-ad184e3f-dcc8-422f-b8cc-738574a4bf01.png)

![Screenshot_20211107-084220~2.png](https://user-images.githubusercontent.com/77606699/140648127-dd95614d-5828-4597-88c5-9befdbc530b1.png)

![Screenshot_20211107-084341~2.png](https://user-images.githubusercontent.com/77606699/140648129-1e2102a9-4b86-4d60-8551-4a59cdf57c3a.png)

**Comment by Jpersh27** [comment]
@CookieJarApps Have you had any chance yet to look into the above 6 screenshots I attached displaying information on the URLs I entered into the VideoDL Console?

**Comment by CookieJarApps** [comment]
I've had a look - it doesn't seem to be a problem with the extractor, but possibly an issue with the app itself, specifically the part that allows you to select the format/resolution to download the video as. Previewing at best quality seems to work correctly. Over the next week, I'll try and see if I can release an update with a fix.

**Comment by Jpersh27** [comment]
@CookieJarApps Thank you again for looking into it. Any idea on when next week you think you'll be able to release a new build that will address the issue?

**Comment by Jpersh27** [comment]
@CookieJarApps Have you had any chance to look into anything yet?

**Comment by Jpersh27** [comment]
Is there anything you can share right now regarding the next application update??? @CookieJarApps

**Comment by Jpersh27** [comment]
@CookieJarApps Any Updates?????

**Comment by CookieJarApps** [comment]
Sorry for the late reply, I haven't really had much time to work on my apps this weekend - I'm still planning to look into this issue soon to see why the app can't download the files, but yt-dlp can.
