### ISSUE TITLE
Can't clear any Downloads from the Downloads List-

### ISSUE THREAD

**Issue by Jpersh27** [CookieJarApps/VideoDL#2]
@CookieJarApps- I've noticed a bug/issue upon further testing and usage of the app today. 

Bug- 

• After downloading a file the download still shows up in the download list and I'm unable to clear it from the list after the file is complete.

• I have to completely reset the app and clear the apps storage and cache to get the downloads list to be cleared. 

Suggestions/Fix-

1.) Ability to swipe away the download when finished and clear it from the screen. 
(Swipe Left or Right over top of the file name to clear it from the list) 

2.) Long press on the download file and give options to either “Remove item from list or “Delete file from device”

Question- 

1.) Will the download button that's integrated in the navbar make the 13.0 beta release later this week or weekend? 

Device information- 

• App version- #0.1.0

• Apk Version- app-arm64-v8a-release.apk

• Device type- Nokia 5.3

• Android version- 10 Q

• Thanks again for the creation of this new app. So far it has worked well with grabbing files from the links I have shared. However I'm really looking forward too and can't wait to try it out once it's integrated within the browser itself.

**Comment by CookieJarApps** [comment]
Thanks for the suggestion, I'll make sure to add this today and post a new release.

**Comment by CookieJarApps** [comment]
Update v0.2.0 is now available and (hopefully) should allow you to delete downloads with a long press.

The download button in the navbar will be included in the v13 beta this weekend.
