### ISSUE TITLE
Update 0.3.0 Release

### ISSUE THREAD

**Issue by Jpersh27** [CookieJarApps/VideoDL#5]
@CookieJarApps- Any news on when or what date this week the new update for VideoDL will be released on? 

• I know previously you said it would be released on Sunday, (March 7th) but I see that two new versions of the Biscuit Browser where released instead.

2.) Will the new update still Include download percentages, download pausing and cancelling and simultaneous downloads? 

3.) Any progress on working on splitting downloads? 

Thanks again.

**Comment by CookieJarApps** [comment]
The update didn't get finished in time, so is pushed back to this weekend. Download percentages are currently working, and I'm going to add pausing and simultaneous downloads later this week.

There isn't any progress on splitting downloads, but I'm still looking into it.

**Comment by Jpersh27** [comment]
@CookieJarApps Any new updates regarding the 0.3.0 update for this weekend? 

1.) Do you have an exact day set on when you plan on releasing the update? 

2.) Lastly any new progress on the splitting Downloads feature? 

Thanks again.

**Comment by legkamran** [comment]
And I suggest add estimated size file before downloading. Currently just showing file type not size :)

**Comment by CookieJarApps** [comment]
> And I suggest add estimated size file before downloading. Currently just showing file type not size :)

Done now in 8cc95bb3a5f7c38d79eeddccef087f6121c65c5f, thanks for the suggestion

**Comment by CookieJarApps** [comment]
> @CookieJarApps Any new updates regarding the 0.3.0 update for this weekend?
> 
> 1.) Do you have an exact day set on when you plan on releasing the update?
> 
> 2.) Lastly any new progress on the splitting Downloads feature?
> 
> Thanks again.

The release will probably be done on Sunday.

I'm adding download pausing / cancelling right now, and after that I'll start working on splitting downloads.
