### ISSUE TITLE
Download Improvements

### ISSUE THREAD

**Issue by Jpersh27** [CookieJarApps/VideoDL#7]
Hello again @CookieJarApps I hope you are doing well!

I do have a few feature suggestions that could help improve the Video DL application. 

• 1: Accelerate download speeds by using multi threading. (Between 16 too 32 parts) 

• 2: Interception of links from android browsers and clipboard to help fill in the “Video URL field"

• 3: While downloading files in the background show a ETA (Estimated time until finished) until the file is finished in the notification bar and under the apps “Downloads section"

(Already the app shows progress from 0 to 100%)

• 4: Create an empty file to accelerate downloading.

• 5: Lastly add option to autoresume after errors and or a break in connection. 

(Resuming of interrupted downloads)

Thank you and I hope you have a nice rest of your day today!

**Comment by CookieJarApps** [comment]
Thanks for the suggestions,
At the moment, downloading is handled internally by the youtube-dl library the app uses, but for the next update, I'll change that so the library just gets the direct video URL and then the app can download the file itself which will allow me to add some more advanced download features.

I'll also add an ETA to the notification and some improvements to the Video URL field (clipboard, preview of video name before submitting query, etc...)

**Comment by Jpersh27** [comment]
@CookieJarApps- Thank you for the reply and thank you for the information.

1.) Any time frame or ETA on when you plan on releasing the newest version (0.4.0) with all the new planned updates?

**Comment by CookieJarApps** [comment]
I'm not 100% sure when I'll have some time to work on VideoDL, I've got to finish the next BiscuitBrowser and SCW updates first which should hopefully be done on Wednesday, so probably the VideoDL update will come the weekend after the next one (25th April).

**Comment by Jpersh27** [comment]
Hello @CookieJarApps

Thank you for the two most recent updates to the VideoDL application and for your continued commitment to improve the application for the community.

1.) I was wondering if you have an update on how things are going regarding my mentioned download Improvements above for the VideoDL application? 

2.) Lastly have you made any progress in adding support for VideoDL in the Biscuit Browser? (As an add-on or support as an external download manager application under advanced settings)

Thank you again and I hope you have a great rest of your week!

**Comment by CookieJarApps** [comment]
1) At the moment, I'm planning to do a rewrite of the app for the first stable version (1.0.0), which will remove the need for an external library.  Then, the app will no longer run into issues like the 'Invalid URL' bug a few days ago, and I'll be able to add some more advanced download features.

2) I haven't entirely decided how to add VideoDL support to BiscuitBrowser, but it will be the next thing I work on, hopefully ready for an update this weekend. I'm leaning towards just implementing it in the same way as SCW (if the browser detects that it's installed, it adds a video download button to the browser toolbar).

**Comment by Jpersh27** [comment]
@CookieJarApps Thank you for the reply and update info. 

1.) Any idea on when you expect to be done with the first stable version (1.0.0) of Video DL?

2.) What other options are you thinking besides what's available currently in SCW? (For you to implement it into Biscuit Browser)

• You could support it as an external download manager under advanced settings.

3.) Anyway or chance you could add it to the list of current available add-ons?

**Comment by CookieJarApps** [comment]
> @CookieJarApps Thank you for the reply and update info.
> 
> 1.) Any idea on when you expect to be done with the first stable version (1.0.0) of Video DL?
> 
> 2.) What other options are you thinking besides what's available currently in SCW? (For you to implement it into Biscuit Browser)
> 
> • You could support it as an external download manager under advanced settings.
> 
> 3.) Anyway or chance you could add it to the list of current available add-ons?

1) I'm not 100% sure, but at the latest, the 8th of May.

2) My current plan is to have the VideoDL app run a webserver that communicates with an add-on in BiscuitBrowser to allow video downloads without leaving the browser.

**Comment by Jpersh27** [comment]
@CookieJarApps Hello I hope all is well with you. 

1.) Any news or updates you can give on the progress you have made towards the first stable 1.0 release of the VideoDL application?

• Since updates 0.3.1 and 0.3.2 I have been have several issues with downloading video files on a number of websites, and have been having trouble playing downloaded files after they are completed because they are showing up as corrupted files. I have encountered this issue of two of my Devices with one running Android 9 Pie and the other Android 10 Q.

**Comment by CookieJarApps** [comment]
> @CookieJarApps Hello I hope all is well with you. 
> 
> 1.) Any news or updates you can give on the progress you have made towards the first stable 1.0 release of the VideoDL application?
> 
> • Since updates 0.3.1 and 0.3.2 I have been have several issues with downloading video files on a number of websites, and have been having trouble playing downloaded files after they are completed because they are showing up as corrupted files. I have encountered this issue of two of my Devices with one running Android 9 Pie and the other Android 10 Q. 

At the moment there aren't any updates. Sorry about the current issues with the app, updates 0.3.1 and 0.3.2 were to fix some issues after YouTube changed something that broke the app. In theory, nothing related to downloading should have changed, but I'll test on my device and if I can recreate the issue I'll release an update ASAP with a fix, as the 1.0 release is still probably a week away.

**Comment by Jpersh27** [comment]
@CookieJarApps Hello,

1.) Are you still planning on releasing the 1.0 build for VideoDL sometime tomorrow? (May the 8th) Or will you have to push back the release to next week? 

2.) Any new updates on how you will implement VideoDL into the Biscuit Browser?

(Previously you said your plan was to have the VideoDL app run a webserver that communicates with an add-on in Biscuit Browser to allow video downloads without leaving the browser)

**Comment by CookieJarApps** [comment]
> @CookieJarApps Hello,
> 
> 1.) Are you still planning on releasing the 1.0 build for VideoDL sometime tomorrow? (May the 8th) Or will you have to push back the release to next week? 
> 
> 2.) Any new updates on how you will implement VideoDL into the Biscuit Browser?
> 
> (Previously you said your plan was to have the VideoDL app run a webserver that communicates with an add-on in Biscuit Browser to allow video downloads without leaving the browser)

I'm still not sure whether I'll finish the update by the end of this weekend, but I'll keep working on it.

I've been playing around with a way to make add-ons communicate with the app, and it looks like it might be a viable way to allow the add-on to communicate with the VideoDL app in some way (VideoDL Add-on <-> SmartCookieWeb Preview <-> VideoDL App). I'll keep looking into it.

**Comment by Jpersh27** [comment]
@CookieJarApps Hello

1.) Do you have an update on the 1.0 build for the VideoDL application? And when you possibly could release it by?

**Comment by CookieJarApps** [comment]
@Jpersh27 I'm working on the update right now. It should be done today or tomorrow and it will include an improved UI, a way to send extracted URLs to apps such as VLC for streaming, download improvements and an updated version of youtubedl.

**Comment by CookieJarApps** [comment]
What I might do, for now, is release a new v1.0 update without some of the new download features today, and add them at a later date in another update, so I can at least get a complete bug-free update out this month. In the mean time, I've added support for external download managers, such as Download Navi which can handle splitting downloads up, in the app's settings.
